Hsys1/src/HSYS/MainBundle/Entity/Unidad.php
<?php

namespace HSYS\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Unidad
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="HSYS\MainBundle\Entity\UnidadRepository")
 */
class Unidad {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="vencimiento", type="date", nullable=true)
     */
    private $vencimiento;

    /**
     * @var \DateTime
     * 
     * @ORM\Column(name="vencimientobolsa", type="date", nullable=true)
     */
    private $vencimientobolsa;
    
    /**
     * @var \DateTime
     * 
     * @ORM\Column(name="fechadescarte", type="date", nullable=true)
     */
    private $fechadescarte;
    
    /**
     * @var \DateTime
     * 
     * @ORM\Column(name="fechadesbloqueo", type="date", nullable=true)
     */
    private $fechadesbloqueo;

    /**
     * @var float
     *
     * @ORM\Column(name="volumen", type="decimal", nullable=true)
     */
    private $volumen;

    /**
     * @var string
     *
     * @ORM\Column(name="idbolsa", type="string", length=20, nullable=true)
     */
    private $idbolsa;

    /**
     * @var string
     *
     * @ORM\Column(name="nrolote", type="string", length=20, nullable=true)
     */
    private $nrolote;

    /**
     * @var string
     *
     * @ORM\Column(name="tipobolsa", type="string", length=20, nullable=true)
     */
    private $tipobolsa;

    /**
     * @var string
     *
     * @ORM\Column(name="marca", type="string", length=30, nullable=true)
     */
    private $marca;

    /**
     * @var string
     *
     * @ORM\Column(name="anticoagulante", type="string", length=20, nullable=true)
     */
    private $anticoagulante;

    /**
     * @var string
     * los estados pueden ser: bloqueado, desbloqueado, transfundido, descartado (=vencimiento??), fraccionado (ojo esto es solo para sangre entera).
     * @ORM\Column(name="estado", type="string", length=30, nullable=true)
     */
    private $estado;

    /**
     * @var string
     *
     * @ORM\Column(name="comentarios", type="text", nullable=true)
     */
    private $comentarios;

    /**
     * @var string
     * 
     * @ORM\Column(name="causadescarte", type="string", length=50, nullable=true)
     */
    private $causadescarte;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set vencimiento
     *
     * @param \DateTime $vencimiento
     * @return Unidad
     */
    public function setVencimiento($vencimiento) {
        $this->vencimiento = $vencimiento;

        return $this;
    }

    /**
     * Get vencimiento
     *
     * @return \DateTime 
     */
    public function getVencimiento() {
        return $this->vencimiento;
    }

    /**
     * Set Vencimientobolsa
     * 
     * @param \DateTime $vencimientobolsa
     * @return Unidad
     */
    public function setVencimientobolsa($vencimientobolsa) {
        $this->vencimientobolsa = $vencimientobolsa;
        return $this;
    }

    /**
     * Get Vencimientobolsa
     * 
     * @return \DateTime
     */
    public function getVencimientobolsa() {
        return $this->vencimientobolsa;
    }
    
    /**
     * Set Fechadescarte
     * 
     * @param \DateTime $fechadescarte
     * @return Unidad
     */
    public function setFechadescarte($fechadescarte) {
        $this->fechadescarte = $fechadescarte;
        return $this;
    }

    /**
     * Get Fechadescarte
     * 
     * @return \DateTime
     */
    public function getFechadescarte() {
        return $this->fechadescarte;
    }
    
    /**
     * Set Fechadesbloqueo
     * 
     * @param \DateTime $fechadesbloqueo
     * @return Unidad
     */
    public function setFechadesbloqueo($fechadesbloqueo) {
        $this->fechadesbloqueo = $fechadesbloqueo;
        return $this;
    }

    /**
     * Get Fechadesbloqueo
     * 
     * @return \DateTime
     */
    public function getFechadesbloqueo() {
        return $this->fechadesbloqueo;
    }

    /**
     * Set volumen
     *
     * @param float $volumen
     * @return Unidad
     */
    public function setVolumen($volumen) {
        $this->volumen = $volumen;

        return $this;
    }

    /**
     * Get volumen
     *
     * @return float 
     */
    public function getVolumen() {
        return $this->volumen;
    }

    /**
     * Set idbolsa
     *
     * @param string $idbolsa
     * @return Unidad
     */
    public function setIdbolsa($idbolsa) {
        $this->idbolsa = $idbolsa;

        return $this;
    }

    /**
     * Get idbolsa
     *
     * @return string 
     */
    public function getIdbolsa() {
        return $this->idbolsa;
    }

    /**
     * Set nrolote
     *
     * @param string $nrolote
     * @return Unidad
     */
    public function setNrolote($nrolote) {
        $this->nrolote = $nrolote;

        return $this;
    }

    /**
     * Get nrolote
     *
     * @return string 
     */
    public function getNrolote() {
        return $this->nrolote;
    }

    /**
     * Set tipobolsa
     *
     * @param string $tipobolsa
     * @return Unidad
     */
    public function setTipobolsa($tipobolsa) {
        $this->tipobolsa = $tipobolsa;

        return $this;
    }

    /**
     * Get tipobolsa
     *
     * @return string 
     */
    public function getTipobolsa() {
        return $this->tipobolsa;
    }

    /**
     * Set marca
     *
     * @param string $marca
     * @return Unidad
     */
    public function setMarca($marca) {
        $this->marca = $marca;

        return $this;
    }

    /**
     * Get marca
     *
     * @return string 
     */
    public function getMarca() {
        return $this->marca;
    }

    /**
     * Set anticoagulante
     *
     * @param string $anticoagulante
     * @return Unidad
     */
    public function setAnticoagulante($anticoagulante) {
        $this->anticoagulante = $anticoagulante;

        return $this;
    }

    /**
     * Get anticoagulante
     *
     * @return string 
     */
    public function getAnticoagulante() {
        return $this->anticoagulante;
    }

    /**
     * Set estado
     *
     * @param string $estado
     * @return Unidad
     */
    public function setEstado($estado) {
        $this->estado = $estado;

        return $this;
    }

    /**
     * Get estado
     *
     * @return string 
     */
    public function getEstado() {
        return $this->estado;
    }

    /**
     * Set comentarios
     *
     * @param string $comentarios
     * @return Unidad
     */
    public function setComentarios($comentarios) {
        $this->comentarios = $comentarios;

        return $this;
    }

    /**
     * Get comentarios
     *
     * @return string 
     */
    public function getComentarios() {
        return $this->comentarios;
    }

    /**
     * @ORM\ManyToOne(targetEntity="Donacion", inversedBy="Unidad")
     * @ORM\JoinColumn(name="Donacion", referencedColumnName="id")
     * @return integer
     */
    private $Donacion;

    public function setDonacion(\HSYS\MainBundle\Entity\Donacion $Donacion) {
        $this->Donacion = $Donacion;
    }

    public function getDonacion() {
        return $this->Donacion;
    }

    /**
     * @ORM\ManyToOne(targetEntity="TipoHemocomponente", inversedBy="Unidad")
     * @ORM\JoinColumn(name="TipoHemocomponente", referencedColumnName="id")
     * @return integer
     */
    private $TipoHemocomponente;

    public function setTipoHemocomponente(\HSYS\MainBundle\Entity\TipoHemocomponente $TipoHemocomponente) {
        $this->TipoHemocomponente = $TipoHemocomponente;
    }

    public function getTipoHemocomponente() {
        return $this->TipoHemocomponente;
    }

    /**
     * @var string
     *
     * @ORM\Column(name="factorsang", type="string", length=20, nullable=true)
     */
    private $factorsang;

    /**
     * Set factorsang
     *
     * @param string $factorsang
     * @return Unidad
     */
    public function setFactorsang($factorsang) {
        $this->factorsang = $factorsang;

        return $this;
    }

    /**
     * Get factorsang
     *
     * @return string 
     */
    public function getFactorsang() {
        return $this->factorsang;
    }

    /**
     * Set causadescarte
     *
     * @param string $causadescarte
     * @return Unidad
     */
    public function setCausadescarte($causadescarte) {
        $this->causadescarte = $causadescarte;

        return $this;
    }

    /**
     * Get causadescarte
     *
     * @return string 
     */
    public function getCausadescarte() {
        return $this->causadescarte;
    }

    public function estadosPosibles() {
        if ($this->estado == "Bloqueado") {
            return array("Desbloqueado", "Descartado", "Fraccionado");
        } else {
            if ($this->estado == "Desbloqueado") {
                return array("Transfundido", "Descartado", "Fraccionado", "Bloqueado");
            } else {
                if ($this->estado == "Transfundido") {
                    return array();
                } else {
                    if ($this->estado == "Descartado") {
                        return array();
                    } else {
                        if ($this->estado == "Fraccionado") {
                            return array();
                        }
                    }
                }
            }
        }
    }

}

Hsys1/src/HSYS/MainBundle/Resources/views/Sangre/bloquear.html.twig
{% extends 'HSYSMainBundle:Sangre:sangrebase.html.twig' %}

{% block title %}Bloquear Unidad{% endblock %}

{% block contenido %}
 
<h3>Bloquear la unidad ID: {{ unidad.id }}</h3><br/>


{% include 'HSYSMainBundle:Sangre:datosdeunidadver.html.twig' with {'unidad': unidad} %}
 
 <form id="buscar_form" name="cambiarestado" method="post" action="{{ path('bloquear_unidad',{'id':unidad.id}) }}">
       <label>Comentarios:</label>
       </br>
       <textarea id="comentarios" name="comentarios" rows="5" style="width: 50%" autofocus="autofocus">{{ unidad.comentarios }}</textarea>
       </br>
       <input type="checkbox" name="bloquear" id="bloquear" onclick="habilitar()"><label>¿Está seguro que desea bloquear la unidad {{unidad.id}}? </label><br>
       <input type="submit" value="Bloquear"/>

</form>

<script src="{{ asset('js/jquery-1.9.1.js') }}"></script>
<script>
$('input[type="submit"]').attr('disabled','disabled');  
function habilitar(){
if (bloquear.checked) {    
    $('input[type="submit"]').removeAttr('disabled');
} else {
    $('input[type="submit"]').attr('disabled','disabled');
    }
    };
</script>
</script>
{%endblock%}

Hsys1/src/HSYS/MainBundle/Resources/views/Sangre/buscaravanzada.html.twig
{% extends 'HSYSMainBundle:Sangre:sangrebase.html.twig' %}

{% block title %}Búsqueda Avanzada{% endblock %}

{% block contenido %}
<h3>Búsqueda Avanzada de Unidades:</h3>
<form id="buscar_form" name="buscar_form" method="post" action="{{ path('buscar_unidad_avanzada') }}">
    <table>
        <tr>
            <label>Desde: </label>
            <input id="desde" name="desde" type="date" style="width: 140px" {#value="{{ "now"|date('Y-m-d') }}"#} autofocus="autofocus"/>
            <label> Hasta: </label>
            <input id="hasta" name="hasta" type="date" style="width: 140px" {#value="{{ "now"|date('Y-m-d') }}"#}/>
        </tr>
        <tr>
            <td><label>Tipo Hemocomponente: </label></td>
            <td><select name="tipo" id="tipo" style="width: 160px">
                    <option value="">TODOS</option>
                    {% for tipohemocomponente in tiposhemocomponentes %}
                    <option value="{{tipohemocomponente.id}}">{{tipohemocomponente}}</option>
                    {% endfor %}
                </select></td>
        </tr>
        <tr>
            <td><label>Estado: </label></td>
            <td><select name="estado" id="estado" style="width: 160px">
                    <option value="">TODOS</option>
                    {% for estado in estados %}
                    <option value="{{estado}}">{{estado}}</option>
                    {% endfor %}
                </select></td>
        </tr>
        <tr>
            <td><input type="submit" value="Buscar"/></td>
        </tr>
    </table>
</form>
<br/>

{% if metodo %}
{% include 'HSYSMainBundle:Sangre:resultados.html.twig' with {'unidades': unidades} %}
{% endif %}



{% endblock %}

Hsys1/src/HSYS/MainBundle/Resources/views/Sangre/buscardonacion.html.twig
{% extends 'HSYSMainBundle:Sangre:sangrebase.html.twig' %}

{% block title %}Buscar{% endblock %}

{% block contenido %}

<h3>Buscar Unidades por Número de Donación:</h3>
    <form id="buscar_form" name="buscar_form" method="post" action="{{ path('buscar_unidad_donacion') }}">
    <table>
        <tr>
            <td><label for="criterio">Código de donación: </label></td>
            <td><input id="buscar" name="buscar" type="text" style="width: 120px" autofocus="autofocus"/></td>   
            <td><input type="submit" value="Buscar"/></td>
        </tr>
    </table>
</form>
<br/>
{% if metodo %}

{% include 'HSYSMainBundle:Sangre:resultados.html.twig' with {'unidades': unidades} %}

{% endif %}

{% endblock %}

Hsys1/src/HSYS/MainBundle/Resources/views/Sangre/buscarfactorsangui.html.twig
{% extends 'HSYSMainBundle:Sangre:sangrebase.html.twig' %}

{% block title %}Buscar Por Factor Sanguíneo{% endblock %}

{% block contenido %}
 <h3>Buscar Unidades Por Factor Sanguíneo:</h3>
    <form id="buscar_form" name="buscar_form" method="post" action="{{ path('buscar_unidad_factorsanguineo') }}">
    <table>
        <tr>
            <td><label for="criterio">Criterio: </label></td>
            <td><select name="buscar" id="buscar" style="width: 160px" autofocus="autofocus">
                    {% for factor in factorsang %}
                    <option value="{{factor}}">{{factor}}</option>
                    {% endfor %}
                </select></td>
            <td><input type="submit" value="Buscar"/></td>
        </tr>
    </table>
</form>
<br/>
{% if metodo %}
{% include 'HSYSMainBundle:Sangre:resultados.html.twig' with {'unidades': unidades} %}
{% endif %}



{% endblock %}

Hsys1/src/HSYS/MainBundle/Resources/views/Sangre/buscarfecha.html.twig
{% extends 'HSYSMainBundle:Sangre:sangrebase.html.twig' %}

{% block title %}Buscar por Fecha de Vencimiento{% endblock %}

{% block contenido %}
 <h3>Buscar Unidades por Fecha de Vencimiento:</h3>
    <form id="buscar_form" name="buscar_form" method="post" action="{{ path('buscar_unidad_fecha') }}">
    <table>
        <tr>
            <td><label>Desde: </label></td>
            <td><input id="desde" name="desde" type="date" style="width: 140px" {#value="{{ "now"|date('Y-m-d') }}"#} autofocus="autofocus"/></td>
            <td style="width: 10px"></td>
            <td><label>Hasta: </label></td>
            <td><input id="hasta" name="hasta" type="date" style="width: 140px" {#value="{{ "now"|date('Y-m-d') }}"#}/></td>
            <td style="width: 10px"></td>
            <td><input type="submit" value="Buscar"/></td>
         </tr>
    </table>
</form>
<br/>

{% if metodo %}
{% include 'HSYSMainBundle:Sangre:resultados.html.twig' with {'unidades': unidades} %}
{% endif %}



{% endblock %}

Hsys1/src/HSYS/MainBundle/Resources/views/Sangre/confirmacion.html.twig
{% extends 'HSYSMainBundle:Sangre:sangrebase.html.twig' %}

{% block title %}Confirmado{% endblock %}

{% block contenido %}
<div class="consulta">
    Enhorabuena, la unidad con el id "{{ id }}" ha sido correctamente {{ accion }}.
</div>
<br/>
<div class="detalle">
    {% if accion == "desbloqueada" %}
        <ul>        
            <li><a href="{{ path('imprimiretiqueta', {'id':id}) }}">Imprimir Etiqueta</a></li>
            <li><a href="{{ path('pagina_sangre') }}">Continuar</a></li>
        </ul>        
    {% else %}
        <ul>        
            <li><a href="{{ path('pagina_sangre') }}">Haga clic aquí para continuar</a></li>
        </ul>
    {% endif %}
    </div>
{% endblock %}

Hsys1/src/HSYS/MainBundle/Resources/views/Sangre/crearfraccionamiento.html.twig
{% extends 'HSYSMainBundle:Sangre:sangrebase.html.twig' %}

{% block title %}Crear un fraccionamiento{% endblock %}

{% block contenido %}
<h3>Datos de la Sangre Entera</h3>
{% include 'HSYSMainBundle:Sangre:datosdeunidadver.html.twig' with {'unidad': unidad} %}
</br>
<h3>Fraccionamiento</h3>
<form id="crearUnidad" name="crearUnidad" method="post" action="{{ path('crearfraccionamiento_unidad',{'id':unidad.id}) }}">
    <table class="detalle">
    <h3>Grupo Sanguíneo</h3>
        <tr>
            <th>AB0 Rh: </th>
            <td><input name="factorsanguineo" id="factorsanguineo" hidden>
                <select name="selectfs" id="selectfs" style="width: 160px" onchange="cambiarfactorsanguineo()">
                        {% for factor in factorsanguineo %}
                        <option id="{{factor}}" value="{{factor}}">{{factor}}</option>
                        {% endfor %}
                </select>    
           </td>
           {% if is_granted('ROLE_MEDICO') %}
           <td id="cambiarfstd">
               <input id="cambiarfs" name="cambiarfs" type="checkbox" onchange="permitircambiarfs()"> ¿Cambiar el AB0 Rh?
           </td>
           {% endif %}
        </tr>
    </table>
        
</br>
    
    <table class="detalle">
        <h3>Agregar nueva unidad</h3>
    <tr>
        <th>Tipo de Hemocomponente: </th>
        <td><select name="tipohemocomponente" id="tipohemocomponente" style="width: 160px" autofocus="autofocus">
                    {% for tipohemocomponente in tiposhemocomponentes %}
                    <option id="{{tipohemocomponente.duracion}}" value="{{tipohemocomponente.id}}">{{tipohemocomponente}}</option>
                    {% endfor %}
                    </select> 
       </td>
    </tr>
    <tr> 
        <th>Volumen: </th>
        <td><input type="number" step="any" min="0" name="volumen" id="volumen" style="width: 160px"/> cc</td>
    </tr>
    <tr> 
        <th>Fecha de extracción: </th>
        <td><input type="date" name="fechaextraccion" id="fechaextraccion" value="{{ unidad.donacion.fechextraccion | date('Y-m-d') }}" style="width: 160px" disabled=""/></td>
    </tr>
    <tr>
        <th>Días de vencimiento: </th>
        <td><input id="cantidaddedias" name="cantidaddedias" disabled type=number onchange="cambiodias()"> 
            <input id="cambiardias" name="cambiardias" type=checkbox onclick="habilitarnumber()"> ¿Cambiar dias?</td>
    </tr>
    <tr>
        <th>Fecha de vencimiento: </th>
        <td><label name="fechavencimiento" id="fechavencimiento"></label></td>
    </tr>
    <tr> 
        <th>Estado: </th>
        <td><label name="estado" id="estado" style="width: 160px">Bloqueado</label></td>
    </tr>
</table>
<br>
<input type="submit" value="Crear unidad"/></td>
</form>

</br>
<form id="verUnidad" name="verUnidad" method="post" action="{{path('confirmacionfracionamiento_unidad',{'id':unidad.id})}}">
    <h3> Unidades Fraccionadas </h3>
    {% include 'HSYSMainBundle:Sangre:resultados.html.twig' with {'unidades': unidades} %}
    <br>
    <input type=button value="Terminar" onclick="aceptar()" /></td>
</form>


<script src="{{ asset('js/jquery-1.9.1.js') }}"></script>
<script>
window.onload = function() {
    if ( "{{unidad.factorsang}}"==""){ 
        $("#cambiarfstd").hide();
        $("<option value='X' selected='selected'>AB0/RhD</option>").insertBefore($("select option")[0]);
        $('input[type="submit"]').attr('disabled','disabled'); 
    }else{
        $("#cambiarfstd").show();
        $('#selectfs').attr('disabled','disabled');
        $('#selectfs').val('{{unidad.factorsang}}');
        cambiarfactorsanguineo();
     } 
};

{#{% if unidad.factorsang is null  %} #}
$("select").change(function(){ 
    $("select option[value='X']").remove();
    $('input[type="submit"]').removeAttr('disabled');
});
{#{%endif%}#}
    
function permitircambiarfs() {
    if (cambiarfs.checked){
        $('#selectfs').removeAttr('disabled');
    }else{
        $('#selectfs').attr('disabled','disabled');
    }
};

function cambiarfactorsanguineo(){
    $("#factorsanguineo").attr("value",$("#selectfs option:selected").attr("value"));
}

$("#tipohemocomponente").change(function(){
        var cantidad = $("#tipohemocomponente option:selected").attr("id");
        $("#cantidaddedias").val(cantidad);
        cambiodias();
});

function cambiodias(){
        var cantidad = $("#cantidaddedias").val();
        if (cantidad <= 0) {
            cantidad++;
            $("#cantidaddedias").val(cantidad);
        } else {
                var fecha1 = $("#fechaextraccion").get(0).value;
                var fecha12 = fecha1.split("-");
                var fe = new Date(fecha12[0],fecha12[1]-1,fecha12[2]);
                var fechactual = fe.valueOf();
                var fechsalida = new Date(fechactual + ( cantidad * 86400000 ) );
                $("#fechavencimiento").text(fechsalida.getDate() + "/" + (fechsalida.getMonth() +1) + "/" + fechsalida.getFullYear());
        }
        $("#cantidaddedias").attr("value",cantidad);
};


function habilitarnumber(){
if (cambiardias.checked) {    
    $('#cantidaddedias').removeAttr('disabled');
} else {
    $('#cantidaddedias').attr('disabled','disabled');
    }
    };
    
    
function aceptar() {
    var pregunta = confirm("¿Desea terminar el Fraccionamiento?");
    if (pregunta){
       $("#verUnidad").submit();
    };
}
</script>
{% endblock %}

Hsys1/src/HSYS/MainBundle/Resources/views/Sangre/datosdeunidadver.html.twig
<table class="detalle">
    <tr>
        <th>Número de Donación: </th>
        <td>{{unidad.donacion.numdedonacion}}</td>
    </tr>
    <tr>
        <th>Código de unidad: </th>
        <td>{{ unidad.id }}</td>
    </tr>
        <tr>
        <th>AB0/Rh(D): </th>
        <td>{{ unidad.factorsang  }}</td>
    </tr>
    <tr>
        <th>Tipo de Hemocomponente: </th>
        <td>{{ unidad.tipohemocomponente }}</td>
    </tr>
    <tr>
        <th>Estado: </th>
        <td>{{ unidad.estado }}</td>
    </tr>
    {% if unidad.estado == 'Descartado' %}
    <tr>
        <th>Causa de descarte: </th>
        <td>{{ unidad.causadescarte }}</td>
    </tr>
    {% endif %}
    <tr>
        <th>Fecha de Extracción: </th>
        <td>{{ unidad.Donacion.fechextraccion | date("d/m/Y")  }}</td>
    </tr>
    <tr>
        <th>Fecha de vencimiento: </th>
        <td>{{ unidad.vencimiento | date("d/m/Y")  }}</td>
    </tr>
    <tr>
        <th>Número de Tubuladura: </th>
        <td>{{ unidad.idbolsa }}</td>
    </tr>
    <tr>
        <th>Número de Lote: </th>
        <td>{{ unidad.nrolote }}</td>
    </tr>
    <tr>
        <th>Tipo de bolsa: </th>
        <td>{{ unidad.tipobolsa }}</td>
    </tr>
    <tr>
        <th>Marca de bolsa: </th>
        <td>{{ unidad.marca }}</td>
    </tr>
    <tr>
        <th>Anticoagulante: </th>
        <td>{{ unidad.anticoagulante }}</td>
    </tr>
    <tr>
        <th>Volumen: </th>
        <td>{{ unidad.volumen }}</td>
    </tr>
</table>
<br/>
<table class="detalle">
        <tr><th>Comentarios: </th></tr>
        <tr><td>{{ unidad.comentarios }}</td></tr>
</table>

Hsys1/src/HSYS/MainBundle/Resources/views/Sangre/index.html.twig
{% extends 'HSYSMainBundle:Sangre:sangrebase.html.twig' %}

{% block title %}Sangre{% endblock %}

{% block contenido %}
    <h3>Buscar Unidades por Número de Donación:</h3>
    <form id="buscar_form" name="buscar_form" method="post" action="{{ path('buscar_unidad_donacion') }}">
    <table>
        <tr>
            <td><label for="criterio">Código de donación: </label></td>
            <td><input id="buscar" name="buscar" type="text" style="width: 120px" autofocus="autofocus"/></td>   
            <td><input type="submit" value="Buscar"/></td>
        </tr>
    </table>
</form>
<br/>
    
{% endblock %}

Hsys1/src/HSYS/MainBundle/Resources/views/Sangre/modificarestado.html.twig
{% extends 'HSYSMainBundle:Sangre:sangrebase.html.twig' %}

{% block title %}Modificar Estado{% endblock %}

{% block contenido %}
 
{% include 'HSYSMainBundle:Sangre:datosdeunidadver.html.twig' with {'unidad': unidad} %}
 
 <form id="buscar_form" name="cambiarestado" method="post" action="{{ path('modificarestado_unidad',{'id':unidad.id}) }}">
     <label>Seleccione el estado al que desea que cambie la unidad: </label>
     <table>
        <tr>
            <td><label for="cambiarestado">Cambiar a Estado: </label></td>
            <td><select name="nuevoestado" id="nuevoestado" style="width: 160px">
                    {% for estado in estados %}
                            {% if estado != unidad.estado %}
                    <option value="{{estado}}">{{estado}}</option>
                        {% endif %}
                    {% endfor %}
                </select></td>
            </tr>
        </table>
         <div name="confirmacion" id="confirmacion"></div>

         <td><input type="submit" value="Cambiar de Estado"/> <label id="respuesta" name="respuesta"></label></td>
</form>
<br/>

<script src="http://code.jquery.com/jquery-latest.js"></script>
<script>
$('input[type="submit"]').attr('disabled','disabled');   
$("<option value='X' selected='selected'></option>").insertBefore($("select option")[0]);

$("#nuevoestado").change(function(){
    $("select option[value='X']").remove();
    $('input[type="submit"]').removeAttr('disabled');    
    var nuevoestado = $("#nuevoestado option:selected").attr("value");
    var viejoestado = "{{unidad.estado}}";
    $("#confirmacion").html("</br><td>Se cambia del estado: <b>{{unidad.estado}}</b>, Al estado: <b>"+nuevoestado+"</b>. </td></br></br>");
});

</script>

{%endblock%}